/**
 * @license Apache-2.0
 * @s2c/export — Synthesis Report Generator (Doc §13).
 */

import type { Circuit, Diagnostic } from "@s2c/circuit-json";
import { formatBomMarkdown, generateBom } from "./bom.js";
import { formatWiringTableMarkdown, generateWiringTable } from "./wiring-table.js";

export interface ReportOptions {
  title?: string;
  sourceFile?: string;
  diagnostics?: Diagnostic[];
  peripherals?: Array<{ kind: string; confidence: number; evidence: string[] }>;
  unresolved?: string[];
}

/**
 * Generates a full markdown synthesis engineering report.
 */
export function generateSynthesisReport(circuit: Circuit, options: ReportOptions = {}): string {
  const diagnostics = options.diagnostics || [];
  const errors = diagnostics.filter((d) => d.severity === "error");
  const warnings = diagnostics.filter((d) => d.severity === "warning");
  const infos = diagnostics.filter((d) => d.severity === "info");

  const wiring = generateWiringTable(circuit);
  const bom = generateBom(circuit);

  const lines: string[] = [
    `# Circuit Synthesis Report: ${options.title || circuit.name || "Arduino Circuit"}`,
    "",
    `*Generated by sketch2circuit on ${circuit.metadata?.generatedAt || new Date().toISOString()}*`,
    options.sourceFile ? `*Source sketch: \`${options.sourceFile}\`*` : "",
    "",
    "## 1. Executive Summary",
    `- **Components:** ${circuit.components.length} parts`,
    `- **Nets:** ${circuit.nets.length} electrical nets`,
    `- **ERC Status:** ${
      errors.length === 0 ? "PASSED (0 Errors)" : `FAILED (${errors.length} Errors)`
    } (${warnings.length} Warnings, ${infos.length} Notices)`,
    "",
  ];

  // ERC breakdown
  lines.push("## 2. Electrical Rules Check (ERC) Diagnostics");
  if (diagnostics.length === 0) {
    lines.push(" All 18 electrical design rules passed cleanly.");
  } else {
    for (const d of diagnostics) {
      const badge =
        d.severity === "error"
          ? "❌ **ERROR**"
          : d.severity === "warning"
            ? "⚠️ **WARN**"
            : "ℹ️ **INFO**";
      lines.push(`### ${badge}: \`${d.ruleId}\``);
      lines.push(`- **Message:** ${d.message}`);
      lines.push(`- **Target:** ${d.target.type} \`${d.target.id}\``);
      if (d.explanation) lines.push(`- **Explanation:** ${d.explanation}`);
      if (d.suggestion) lines.push(`- **Remediation:** ${d.suggestion}`);
      lines.push("");
    }
  }

  // Unresolved items if any
  if (options.unresolved && options.unresolved.length > 0) {
    lines.push("## 3. Unresolved Dynamic Items (Doc §12.8)");
    lines.push(
      "The following code elements could not be statically resolved and were not guessed:",
    );
    for (const u of options.unresolved) {
      lines.push(`- ⚠️ ${u}`);
    }
    lines.push("");
  }

  // Wiring Table
  lines.push("## 4. Hardware Wiring Table");
  lines.push(formatWiringTableMarkdown(wiring));
  lines.push("");

  // Bill of Materials
  lines.push("## 5. Bill of Materials (BOM)");
  lines.push(formatBomMarkdown(bom));
  lines.push("");

  return lines.filter(Boolean).join("\n");
}
