/**
 * @license Apache-2.0
 * @s2c/export-ato — Atopile (.ato) Generator (Doc §15).
 * Generates idiomatic, compiler-compliant .ato modules from sketch2circuit IR.
 */

import type { Circuit } from "@s2c/circuit-json";
import { ATO_COMPONENT_DEFINITIONS, resolveAtoPart } from "./part-map.js";
import type { AtoExportOptions } from "./types.js";

/**
 * Converts a synthesized Circuit IR into a production-grade atopile (.ato) source file.
 */
export function circuitToAto(circuit: Circuit, options: AtoExportOptions = {}): string {
  const moduleName =
    options.moduleName ||
    sanitizeAtoIdentifier(
      circuit.name || circuit.metadata?.sketchName || "SynthesizedCircuit",
      true,
    );

  // Deterministically sort components and nets
  const components = [...circuit.components].sort((a, b) => a.id.localeCompare(b.id));
  const nets = [...circuit.nets].sort((a, b) => a.id.localeCompare(b.id));

  // 1. Analyze components and resolve part references
  const compRefs = new Map<string, ReturnType<typeof resolveAtoPart>>();
  const stdLibImports = new Set<string>();
  const customComponentDefs = new Set<string>();

  for (const comp of components) {
    const ref = resolveAtoPart(comp);
    compRefs.set(comp.id, ref);
    if (ref.isStdLib) {
      stdLibImports.add(ref.componentType);
    } else if (ATO_COMPONENT_DEFINITIONS[ref.componentType]) {
      customComponentDefs.add(ref.componentType);
    }
  }

  const lines: string[] = [];

  // Header banner
  lines.push("# =============================================================================");
  lines.push("# Generated by sketch2circuit @s2c/export-ato (Doc §15)");
  lines.push(
    "# Fully declarative atopile (.ato) hardware description compiled from Arduino sketch",
  );
  if (options.timestamp) {
    lines.push(`# Timestamp: ${options.timestamp}`);
  }
  lines.push("# =============================================================================");
  lines.push("");

  // Atopile standard library imports
  const sortedStdImports = Array.from(stdLibImports).sort();
  if (sortedStdImports.length > 0) {
    lines.push("# Standard library imports");
    for (const imp of sortedStdImports) {
      lines.push(`import ${imp}`);
    }
    lines.push("");
  }

  // Custom component definitions (headers, modules, specialized sensors)
  if (options.includeComponentDefinitions !== false && customComponentDefs.size > 0) {
    lines.push("# =============================================================================");
    lines.push("# Custom Component & Interface Definitions");
    lines.push("# =============================================================================");
    lines.push("");
    const sortedDefs = Array.from(customComponentDefs).sort();
    for (const defName of sortedDefs) {
      const defCode = ATO_COMPONENT_DEFINITIONS[defName];
      if (defCode) {
        lines.push(defCode);
        lines.push("");
      }
    }
  }

  // Main Module
  lines.push("# =============================================================================");
  lines.push(`# Module: ${moduleName}`);
  lines.push("# =============================================================================");
  lines.push(`module ${moduleName}:`);

  const indent = "    ";

  if (options.includeDocstrings !== false) {
    const title = circuit.name || circuit.metadata?.sketchName || "Arduino Synthesized Circuit";
    const desc = circuit.metadata?.description || "Compiled by sketch2circuit";
    lines.push(`${indent}"""`);
    lines.push(`${indent}${title}`);
    lines.push(`${indent}${desc}`);
    lines.push(`${indent}Components: ${components.length} | Nets: ${nets.length}`);
    lines.push(`${indent}"""`);
    lines.push("");
  }

  // Track global power signals
  const hasGnd = nets.some(
    (n) =>
      n.id.toUpperCase() === "GND" ||
      n.portIds.some((p) => p.includes(".GND") || p.endsWith(".K") || p.endsWith(".2")),
  );
  const has5V = nets.some(
    (n) =>
      n.id.toUpperCase() === "5V" ||
      n.id.toUpperCase() === "VCC" ||
      n.portIds.some((p) => p.endsWith(".5V") || p.endsWith(".VCC")),
  );
  const has3V3 = nets.some(
    (n) => n.id.toUpperCase() === "3V3" || n.portIds.some((p) => p.endsWith(".3V3")),
  );

  lines.push(`${indent}# --- Global Signals ---`);
  if (hasGnd) {
    lines.push(`${indent}signal GND`);
  }
  if (has5V) {
    lines.push(`${indent}signal VCC_5V`);
  }
  if (has3V3) {
    lines.push(`${indent}signal VCC_3V3`);
  }
  lines.push("");

  // Instantiate Components
  lines.push(`${indent}# --- Components ---`);
  for (const comp of components) {
    const ref = compRefs.get(comp.id);
    if (!ref) continue;
    const atoInst = sanitizeAtoInstanceId(comp.id);

    lines.push(`${indent}# ${comp.id}: ${comp.name} (${comp.kind})`);
    lines.push(`${indent}${atoInst} = new ${ref.componentType}`);

    // Constraints & verified part references
    if (ref.valueConstraint) {
      if (ref.componentType === "Resistor") {
        lines.push(`${indent}${atoInst}.resistance = ${ref.valueConstraint}`);
      } else if (ref.componentType === "Capacitor") {
        lines.push(`${indent}${atoInst}.capacitance = ${ref.valueConstraint}`);
      }
    }

    if (ref.packageHint) {
      lines.push(`${indent}${atoInst}.package = "${ref.packageHint}"`);
    }

    // Verified part references (LCSC / MPN / Manufacturer)
    if (ref.verified && ref.lcscId) {
      lines.push(`${indent}${atoInst}.lcsc_id = "${ref.lcscId}"`);
      if (ref.mpn) lines.push(`${indent}${atoInst}.mpn = "${ref.mpn}"`);
      if (ref.manufacturer) lines.push(`${indent}${atoInst}.manufacturer = "${ref.manufacturer}"`);
    } else if (ref.mpn && !ref.verified) {
      lines.push(`${indent}${atoInst}.mpn = "${ref.mpn}"`);
      if (ref.manufacturer) lines.push(`${indent}${atoInst}.manufacturer = "${ref.manufacturer}"`);
    }

    if (ref.comment) {
      lines.push(`${indent}# ${ref.comment}`);
    }

    lines.push("");
  }

  // Net connections
  lines.push(`${indent}# --- Net Connections ---`);
  const createdLocalSignals = new Set<string>();

  for (const net of nets) {
    const netIdUpper = net.id.toUpperCase();
    const isGndNet = netIdUpper === "GND" || net.portIds.some((p) => p.endsWith(".GND"));
    const is5VNet =
      netIdUpper === "5V" ||
      netIdUpper === "VCC" ||
      net.portIds.some((p) => p.endsWith(".5V") || p.endsWith(".VCC"));
    const is3V3Net = netIdUpper === "3V3" || net.portIds.some((p) => p.endsWith(".3V3"));

    // Map each portId (e.g. "U1.D13") to atopile pin reference (e.g. "u1.D13")
    const resolvedPorts = net.portIds
      .map((p) => resolveAtoPortAccess(p, compRefs))
      .filter((p): p is string => Boolean(p));

    if (resolvedPorts.length === 0) continue;

    if (isGndNet) {
      lines.push(`${indent}# Net: GND (${net.id})`);
      for (const portRef of resolvedPorts) {
        lines.push(`${indent}${portRef} ~ GND`);
      }
      lines.push("");
      continue;
    }

    if (is5VNet) {
      lines.push(`${indent}# Net: 5V Rail (${net.id})`);
      for (const portRef of resolvedPorts) {
        lines.push(`${indent}${portRef} ~ VCC_5V`);
      }
      lines.push("");
      continue;
    }

    if (is3V3Net) {
      lines.push(`${indent}# Net: 3.3V Rail (${net.id})`);
      for (const portRef of resolvedPorts) {
        lines.push(`${indent}${portRef} ~ VCC_3V3`);
      }
      lines.push("");
      continue;
    }

    // Two-endpoint signal net: direct wire connection (e.g. u1.D13 ~ r1.p1)
    if (resolvedPorts.length === 2) {
      let [p1, p2] = resolvedPorts;
      // If p2 is an MCU pin (e.g. u1.D13) and p1 is not, order MCU first for idiomatic readability
      if (/^u[0-9_]/i.test(p2) && !/^u[0-9_]/i.test(p1)) {
        [p1, p2] = [p2, p1];
      }
      lines.push(`${indent}# Net: ${net.id}`);
      lines.push(`${indent}${p1} ~ ${p2}`);
      lines.push("");
      continue;
    }

    // Multi-point signal net (3+ endpoints): declare local signal and connect endpoints
    const sigName = sanitizeAtoIdentifier(`sig_${net.id}`);
    if (!createdLocalSignals.has(sigName)) {
      createdLocalSignals.add(sigName);
      lines.push(`${indent}# Multi-point Net: ${net.id}`);
      lines.push(`${indent}signal ${sigName}`);
      for (const portRef of resolvedPorts) {
        lines.push(`${indent}${portRef} ~ ${sigName}`);
      }
      lines.push("");
    }
  }

  return `${lines.join("\n")}\n`;
}

/**
 * Resolves a circuit portId (e.g. "U1.D13", "R1.1", "D1.A") into atopile pin syntax (e.g. "u1.D13", "r1.p1", "d1.anode").
 */
function resolveAtoPortAccess(
  portId: string,
  compRefs: Map<string, ReturnType<typeof resolveAtoPart>>,
): string | null {
  const dotIdx = portId.indexOf(".");
  if (dotIdx === -1) return null;

  const compId = portId.slice(0, dotIdx);
  const rawPort = portId.slice(dotIdx + 1);

  const ref = compRefs.get(compId);
  if (!ref) return null;

  const instId = sanitizeAtoInstanceId(compId);

  // Check port mapping
  let atoPin = ref.portMap[rawPort];
  if (!atoPin) {
    if (rawPort === "+" || rawPort === "pos") {
      atoPin = "pos";
    } else if (rawPort === "-" || rawPort === "neg") {
      atoPin = "neg";
    } else if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(rawPort)) {
      atoPin = rawPort;
    } else {
      const sanitized = rawPort.replace(/[^A-Za-z0-9_]/g, "_");
      atoPin = `p${sanitized}`;
    }
  }

  return `${instId}.${atoPin}`;
}

/**
 * Sanitizes component ID into valid lowercase atopile instance variable (e.g. "U1" -> "u1", "C_SERVO1" -> "c_servo1").
 */
function sanitizeAtoInstanceId(id: string): string {
  let s = id.toLowerCase().replace(/[^a-z0-9_]/g, "_");
  if (/^[0-9]/.test(s)) {
    s = `comp_${s}`;
  }
  return s;
}

/**
 * Sanitizes a title into a valid PascalCase module or signal identifier.
 */
function sanitizeAtoIdentifier(name: string, pascalCase = false): string {
  const cleaned = name.replace(/[^a-zA-Z0-9_]/g, " ").trim();
  const words = cleaned.split(/\s+/).filter(Boolean);
  if (words.length === 0) return "SynthesizedCircuit";

  if (pascalCase) {
    return words.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join("");
  }
  return words.join("_").toUpperCase();
}
