/**
 * @license Apache-2.0
 * @s2c/arduino — Milestone 15: MATLAB / Simulink Code Parser Support Tests.
 *
 * Verifies that C/C++ code generated by MATLAB/Simulink Embedded Coder for Arduino:
 * 1. Accurately extracts hardware facts from MW_* wrappers (MW_pinMode, MW_digitalIO_write, etc.)
 * 2. Parses block comments and associates them as name hints
 * 3. Successfully synthesizes into valid Circuit IR with correct I/O pins and modes
 */

import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { extractFacts } from "../src/extract-facts.js";
import { synthesizeSketch } from "../src/synthesizer.js";

describe("Milestone 15: MATLAB/Simulink Code Parser Support", () => {
  const fixturePath = path.resolve(process.cwd(), "fixtures/sketches/simulink_mock.cpp");
  const simulinkSource = fs.readFileSync(fixturePath, "utf-8");

  it("extracts facts accurately from MW_* Simulink wrappers and block comments", () => {
    const facts = extractFacts(simulinkSource);

    // 1. Headers
    expect(facts.includes).toContain("simulink_mock.h");
    expect(facts.includes).toContain("MW_target_hardware_resources.h");
    expect(facts.includes).toContain("MW_arduino_digitalio.h");
    expect(facts.includes).toContain("MW_PWM.h");

    // 2. Calls extraction: MW_pinMode -> pinMode
    const pinModeCalls = facts.calls.filter((c) => c.name === "pinMode");
    expect(pinModeCalls.length).toBeGreaterThanOrEqual(3);

    // Pin 13 pinMode OUTPUT
    const pin13Mode = pinModeCalls.find((c) => c.args[0] === 13);
    expect(pin13Mode).toBeDefined();
    expect(pin13Mode?.args[1]).toBe("MW_OUTPUT");

    // Pin 2 pinMode INPUT_PULLUP
    const pin2Mode = pinModeCalls.find((c) => c.args[0] === 2);
    expect(pin2Mode).toBeDefined();
    expect(pin2Mode?.args[1]).toBe("MW_INPUT_PULLUP");

    // Pin 9 pinMode OUTPUT (PWM)
    const pin9Mode = pinModeCalls.find((c) => c.args[0] === 9);
    expect(pin9Mode).toBeDefined();

    // 3. Calls extraction: MW_digitalIO_write -> digitalWrite
    const digitalWrites = facts.calls.filter((c) => c.name === "digitalWrite");
    expect(digitalWrites.length).toBeGreaterThanOrEqual(1);
    expect(digitalWrites.some((c) => c.args[0] === 13)).toBe(true);

    // 4. Calls extraction: MW_digitalIO_read -> digitalRead
    const digitalReads = facts.calls.filter((c) => c.name === "digitalRead");
    expect(digitalReads.length).toBeGreaterThanOrEqual(1);
    expect(digitalReads.some((c) => c.args[0] === 2)).toBe(true);

    // 5. Calls extraction: MW_PWM_write -> analogWrite
    const analogWrites = facts.calls.filter((c) => c.name === "analogWrite");
    expect(analogWrites.length).toBeGreaterThanOrEqual(1);
    expect(analogWrites.some((c) => c.args[0] === 9)).toBe(true);

    // 6. Comment hints from Simulink block comments
    expect(facts.commentHints.size).toBeGreaterThan(0);
    const commentTexts = Array.from(facts.commentHints.values()).join(" ");
    expect(commentTexts).toContain("<Root>/Digital Output");
    expect(commentTexts).toContain("<Root>/Digital Input");
    expect(commentTexts).toContain("<Root>/PWM");
  });

  it("synthesizes Simulink-generated Arduino C++ into Circuit IR without errors", () => {
    const result = synthesizeSketch(simulinkSource, { boardId: "ARDUINO_UNO_R3" });

    // 1. Must synthesize without throwing and with peripherals identified
    expect(result.peripherals.length).toBeGreaterThanOrEqual(3);

    // Verify identified peripheral pins
    const pinsInferred = result.peripherals.map((p) => p.pins.pin);
    expect(pinsInferred).toContain("D13");
    expect(pinsInferred).toContain("D2");
    expect(pinsInferred).toContain("D9");

    // 2. Check inferred peripheral kinds
    const ledD13 = result.peripherals.find((p) => p.pins.pin === "D13");
    expect(ledD13).toBeDefined();
    expect(ledD13?.kind).toBe("led");

    const btnD2 = result.peripherals.find((p) => p.pins.pin === "D2");
    expect(btnD2).toBeDefined();
    expect(btnD2?.kind).toBe("button");

    const pwmD9 = result.peripherals.find((p) => p.pins.pin === "D9");
    expect(pwmD9).toBeDefined();
    expect(pwmD9?.kind).toBe("led"); // PWM output inferred as dimmed LED/actuator

    // 3. Pin usage graph verification
    const pin13Use = result.pinGraph.get("D13");
    expect(pin13Use).toBeDefined();
    expect(pin13Use?.modes.has("OUTPUT")).toBe(true);
    expect(pin13Use?.ops.has("digitalWrite")).toBe(true);
    expect(pin13Use?.nameHints.some((h) => h.includes("Digital Output"))).toBe(true);

    const pin2Use = result.pinGraph.get("D2");
    expect(pin2Use).toBeDefined();
    expect(pin2Use?.modes.has("INPUT_PULLUP")).toBe(true);
    expect(pin2Use?.ops.has("digitalRead")).toBe(true);

    const pin9Use = result.pinGraph.get("D9");
    expect(pin9Use).toBeDefined();
    expect(pin9Use?.modes.has("OUTPUT")).toBe(true);
    expect(pin9Use?.ops.has("analogWrite")).toBe(true);

    // 4. Circuit IR components: U1, LEDs, Resistors, Button
    const componentIds = result.circuit.components.map((c) => c.id);
    expect(componentIds).toContain("U1"); // Arduino Uno Board
    expect(componentIds.some((id) => id.startsWith("D"))).toBe(true); // LED
    expect(componentIds.some((id) => id.startsWith("SW"))).toBe(true); // Switch/Button
    expect(componentIds.some((id) => id.startsWith("R"))).toBe(true); // Series Resistor

    // 5. Unrecognized library diagnostics: should NOT warn about Simulink headers
    const libWarnings = result.diagnostics.filter(
      (d) => d.ruleId === "synthesis.unrecognized-library",
    );
    expect(libWarnings.length).toBe(0);

    // 6. Board mismatch: should NOT trigger board mismatch on Uno
    const mismatchWarnings = result.diagnostics.filter(
      (d) => d.ruleId === "synthesis.board-architecture-mismatch",
    );
    expect(mismatchWarnings.length).toBe(0);
  });

  it("handles standalone Simulink snippets with MW_digitalIO_open and MW_pinModeOutput", () => {
    const snippet = `
#include "MW_arduino_digitalio.h"
void setup() {
  MW_pinModeOutput(8);
  MW_digitalIO_open(7, 1);
  MW_digitalIO_write(8, 1);
  MW_digitalIO_write(7, 0);
}
void loop() {}
`;
    const result = synthesizeSketch(snippet, { boardId: "ARDUINO_UNO_R3" });
    expect(result.peripherals.length).toBe(2);
    expect(result.pinGraph.has("D8")).toBe(true);
    expect(result.pinGraph.has("D7")).toBe(true);
    expect(result.pinGraph.get("D8")?.modes.has("OUTPUT")).toBe(true);
    expect(result.pinGraph.get("D7")?.modes.has("OUTPUT")).toBe(true);
  });
});
