/**
 * @license Apache-2.0
 * @s2c/arduino — Main Sketch-to-Circuit Synthesis Pipeline (Doc §12).
 */

import { createCircuit } from "@s2c/core";
import { runErc } from "@s2c/rules";
import { extractFacts } from "./extract-facts.js";
import { inferPeripherals } from "./infer.js";
import { buildPinUsageGraph } from "./pin-graph.js";
import { applyRecipes } from "./recipes/index.js";
import type { SynthesisResult, SynthesizerOptions, UnresolvedItem } from "./types.js";

/**
 * Synthesizes a verified, ERC-checked Electronic Circuit from an Arduino sketch.
 *
 * Sub-steps (Doc §12):
 * 1. Preprocess & extract annotations/macros
 * 2. Parse C++ syntax tree with Tree-sitter
 * 3. Extract facts (pinMode, digitalWrite, analogRead, pulseIn, constructors)
 * 4. Resolve constants and array indices
 * 5. Build pin-usage graph (tracking unresolved dynamic pins)
 * 6. Infer peripherals with confidence scoring & evidence
 * 7. Apply circuit engineering synthesis recipes
 * 8. Run 18-rule Electrical Rules Check (ERC) validation
 * 9. Deterministic normalization (guarantees byte-identical Circuit IR across runs)
 */
export function synthesizeSketch(
  source: string,
  options: SynthesizerOptions = {},
): SynthesisResult {
  const boardId = options.boardId || "ARDUINO_UNO_R3";
  const boardRef = options.boardRef || "U1";

  // 1-3. Extract syntactic facts from sketch via Tree-sitter AST
  const facts = extractFacts(source);

  // 4-5. Build pin usage graph with resolved constants and track unresolved items
  const unresolvedItems: UnresolvedItem[] = [];
  const pinGraph = buildPinUsageGraph(facts, unresolvedItems);

  // 6. Infer connected peripheral hardware
  const {
    peripherals,
    assumptions,
    unresolved: inferUnresolved,
  } = inferPeripherals(pinGraph, facts);

  // Merge unresolved items
  const combinedUnresolved = [...inferUnresolved, ...unresolvedItems.map((u) => u.reason)];

  // 7. Synthesize circuit with engineering recipes
  const builder = createCircuit({
    title: "Synthesized Arduino Circuit",
    description: "Generated by sketch2circuit synthesizer pipeline",
  });

  // Add the microcontroller board
  builder.addPart(boardId, boardRef);

  // Apply component and wiring recipes
  applyRecipes(builder, peripherals, {
    ...options,
    boardId,
    boardRef,
  });

  const rawCircuit = builder.build();

  // Deterministically sort components, nets, and portIds per Doc §12.5
  const components = [...rawCircuit.components].sort((a, b) => a.id.localeCompare(b.id));
  const nets = [...rawCircuit.nets]
    .map((net) => ({
      ...net,
      portIds: [...net.portIds].sort(),
    }))
    .sort((a, b) => a.id.localeCompare(b.id));

  const circuit = {
    ...rawCircuit,
    metadata: {
      ...rawCircuit.metadata,
      ...(options.timestamp ? { generatedAt: options.timestamp } : {}),
    },
    components,
    nets,
  };

  // Deterministically sort peripherals
  const sortedPeripherals = [...peripherals].sort((a, b) => a.id.localeCompare(b.id));

  // 8. Run Electrical Rules Check (ERC) validation across full 18-rule catalog
  const diagnostics = runErc(circuit);

  return {
    circuit,
    peripherals: sortedPeripherals,
    pinGraph,
    diagnostics,
    assumptions,
    unresolved: combinedUnresolved,
    unresolvedItems,
  };
}
