/**
 * @license Apache-2.0
 * @s2c/arduino — Main Sketch-to-Circuit Synthesis Pipeline (Doc §12).
 */

import { createCircuit } from "@s2c/core";
import { runErc } from "@s2c/rules";
import { extractFacts } from "./extract-facts.js";
import { inferPeripherals } from "./infer.js";
import { buildPinUsageGraph } from "./pin-graph.js";
import { applyRecipes } from "./recipes/index.js";
import type { SynthesisResult, SynthesizerOptions, UnresolvedItem } from "./types.js";

/**
 * Synthesizes a verified, ERC-checked Electronic Circuit from an Arduino sketch.
 *
 * Sub-steps (Doc §12):
 * 1. Preprocess & extract annotations/macros
 * 2. Parse C++ syntax tree with Tree-sitter
 * 3. Extract facts (pinMode, digitalWrite, analogRead, pulseIn, constructors)
 * 4. Resolve constants and array indices
 * 5. Build pin-usage graph (tracking unresolved dynamic pins)
 * 6. Infer peripherals with confidence scoring & evidence
 * 7. Apply circuit engineering synthesis recipes
 * 8. Run 18-rule Electrical Rules Check (ERC) validation
 * 9. Deterministic normalization (guarantees byte-identical Circuit IR across runs)
 */
export function synthesizeSketch(
  source: string,
  options: SynthesizerOptions = {},
): SynthesisResult {
  const boardId = options.boardId || "ARDUINO_UNO_R3";
  const boardRef = options.boardRef || "U1";

  // 1-3. Extract syntactic facts from sketch via Tree-sitter AST
  const facts = extractFacts(source);

  // 4-5. Build pin usage graph with resolved constants and track unresolved items
  const unresolvedItems: UnresolvedItem[] = [];
  const pinGraph = buildPinUsageGraph(facts, unresolvedItems);

  // 6. Infer connected peripheral hardware
  const {
    peripherals,
    assumptions,
    unresolved: inferUnresolved,
  } = inferPeripherals(pinGraph, facts);

  // Merge unresolved items
  const combinedUnresolved = [...inferUnresolved, ...unresolvedItems.map((u) => u.reason)];

  // 7. Synthesize circuit with engineering recipes
  const builder = createCircuit({
    title: "Synthesized Arduino Circuit",
    description: "Generated by sketch2circuit synthesizer pipeline",
  });

  // Add the microcontroller board
  builder.addPart(boardId, boardRef);

  // Apply component and wiring recipes
  applyRecipes(builder, peripherals, {
    ...options,
    boardId,
    boardRef,
  });

  const rawCircuit = builder.build();

  // Deterministically sort components, nets, and portIds per Doc §12.5
  const components = [...rawCircuit.components].sort((a, b) => a.id.localeCompare(b.id));
  const nets = [...rawCircuit.nets]
    .map((net) => ({
      ...net,
      portIds: [...net.portIds].sort(),
    }))
    .sort((a, b) => a.id.localeCompare(b.id));

  const circuit = {
    ...rawCircuit,
    metadata: {
      ...rawCircuit.metadata,
      ...(options.timestamp ? { generatedAt: options.timestamp } : {}),
    },
    components,
    nets,
  };

  // Deterministically sort peripherals
  const sortedPeripherals = [...peripherals].sort((a, b) => a.id.localeCompare(b.id));

  // 8. Run Electrical Rules Check (ERC) validation across full 18-rule catalog
  const diagnostics = runErc(circuit);

  // -------------------------------------------------------------------------
  // Check A: Unrecognized #include Libraries (Doc §1.4 / §12.8 / §16)
  // -------------------------------------------------------------------------
  const RECOGNIZED_LIBRARIES = new Set([
    "servo.h",
    "wire.h",
    "spi.h",
    "adafruit_neopixel.h",
    "liquidcrystal.h",
    "liquidcrystal_i2c.h",
    "dht.h",
    "softwareserial.h",
    "arduino.h",
  ]);

  for (const inc of facts.includes) {
    const clean = inc.toLowerCase().trim();
    // MathWorks / Simulink generated wrapper headers (MW_*) or model header files
    if (clean.startsWith("mw_") || clean.includes("simulink") || clean.endsWith("_mock.h")) {
      continue;
    }
    if (!RECOGNIZED_LIBRARIES.has(clean)) {
      const incMsg = `Unrecognized library '#include <${inc}>' is outside current synthesizer v1 scope.`;
      combinedUnresolved.push(incMsg);
      unresolvedItems.push({
        expression: `#include <${inc}>`,
        reason: incMsg,
        range: { startLine: 1, startCol: 1, endLine: 1, endCol: 1 },
      });
      diagnostics.push({
        ruleId: "synthesis.unrecognized-library",
        severity: "warning",
        message: incMsg,
        explanation: `sketch2circuit v1 targets standard Arduino Uno R3 peripherals. Hardware defined solely through '${inc}' cannot be automatically synthesized without '@s2c:' annotations.`,
        target: { type: "circuit", id: "circuit" },
        suggestion: `Annotate circuit peripherals using inline '@s2c: <type>' comments (e.g. '// @s2c: i2c device=oled') or wire components manually.`,
      });
    }
  }

  // -------------------------------------------------------------------------
  // Check B: Pin Numbers Outside Target Board Valid Range (Doc §12.3 / §12.8)
  // -------------------------------------------------------------------------
  const outOfRangePins = new Set<number>();
  for (const pinUse of pinGraph.values()) {
    if (pinUse.pinNumber >= 20 || pinUse.pinNumber < 0) {
      outOfRangePins.add(pinUse.pinNumber);
    }
  }
  const PIN_FUNCS = new Set([
    "pinmode",
    "digitalwrite",
    "digitalread",
    "analogread",
    "analogwrite",
    "attach",
    "mw_pinmodeoutput",
    "mw_pinmodeinput",
    "mw_digitalio_open",
    "mw_digitalio_write",
  ]);
  for (const call of facts.calls) {
    if (PIN_FUNCS.has(call.name.toLowerCase())) {
      const pinArg = call.args[0];
      if (typeof pinArg === "number" && (pinArg >= 20 || pinArg < 0)) {
        outOfRangePins.add(pinArg);
      }
    }
  }
  for (const [k, v] of facts.constants.entries()) {
    if (typeof v === "number" && (v >= 20 || v < 0)) {
      if (/pin|gpio|sda|scl|rx|tx|relay|btn|led/i.test(k)) {
        outOfRangePins.add(v);
      }
    }
  }

  if (outOfRangePins.size > 0 && boardId === "ARDUINO_UNO_R3") {
    for (const pinNum of Array.from(outOfRangePins).sort((a, b) => a - b)) {
      const pinMsg = `Pin ${pinNum}: not a valid Arduino Uno pin (0-13, A0-A5). This sketch may target a different board (ESP32?).`;
      if (!combinedUnresolved.includes(pinMsg)) {
        combinedUnresolved.push(pinMsg);
      }
      unresolvedItems.push({
        expression: String(pinNum),
        reason: pinMsg,
        range: { startLine: 1, startCol: 1, endLine: 1, endCol: 1 },
      });
      diagnostics.push({
        ruleId: "synthesis.pin-out-of-range",
        severity: "warning",
        message: pinMsg,
        explanation: `Arduino Uno R3 only provides digital pins 0-13 and analog pins A0-A5 (14-19). Pin ${pinNum} is outside the microcontroller pin map.`,
        target: { type: "circuit", id: "circuit" },
        suggestion: `Remap pin ${pinNum} to an available Uno pin (0-13, A0-A5) or check your target microcontroller architecture.`,
      });
    }
  }

  // -------------------------------------------------------------------------
  // Check C: Board Architecture Mismatch Heuristic (ESP32 Signals)
  // -------------------------------------------------------------------------
  const espSignals: string[] = [];
  const ESP_INCLUDES = [
    "wifi.h",
    "wificlient.h",
    "wifiserver.h",
    "webserver.h",
    "httpclient.h",
    "preferences.h",
    "bluetoothserial.h",
    "esp_wifi.h",
    "esp_now.h",
    "esp32servo.h",
    "driver/gpio.h",
    "esp_camera.h",
    "asynctcp.h",
    "espasyncwebserver.h",
  ];
  for (const inc of facts.includes) {
    const clean = inc.toLowerCase().trim();
    if (ESP_INCLUDES.some((espInc) => clean.includes(espInc))) {
      espSignals.push(`#include <${inc}>`);
    }
  }
  for (const p of outOfRangePins) {
    if (p >= 20) {
      espSignals.push(`GPIO ${p}`);
    }
  }

  if (boardId === "ARDUINO_UNO_R3" && espSignals.length > 0) {
    const mismatchMsg = `Board Architecture Mismatch: Sketch appears to target ESP32, but target board is Arduino Uno R3.`;
    const mismatchExp = `Detected ESP32 signatures: ${espSignals.join(", ")}. Arduino Uno R3 operates at 5V logic and only provides 14 digital pins (0-13) and 6 analog inputs (A0-A5). ESP32 GPIOs and network libraries cannot be synthesized onto an Uno shield layout.`;
    diagnostics.unshift({
      ruleId: "synthesis.board-architecture-mismatch",
      severity: "warning",
      message: mismatchMsg,
      explanation: mismatchExp,
      target: { type: "circuit", id: "circuit" },
      suggestion:
        "This sketch targets an ESP32 board which is outside sketch2circuit v1 scope (Arduino Uno R3 only). To use with Uno, target standard Uno pins (0-13, A0-A5) and peripherals.",
    });
    combinedUnresolved.unshift(
      `Board Architecture Mismatch: Detected ESP32 signatures (${espSignals.join(", ")}); current target is Arduino Uno R3.`,
    );
  }

  // -------------------------------------------------------------------------
  // Check D: Zero Synthesized Components Notice
  // -------------------------------------------------------------------------
  if (sortedPeripherals.length === 0) {
    const zeroMsg =
      "Zero peripheral components synthesized: Sketch does not contain recognized peripheral hardware signatures or valid Uno pin operations.";
    if (!combinedUnresolved.includes(zeroMsg)) {
      combinedUnresolved.push(zeroMsg);
    }
  }

  // Check for bare motor peripherals driving GPIO directly without driver or flyback
  for (const p of sortedPeripherals) {
    if (p.properties?.isBareMotor) {
      diagnostics.push({
        ruleId: "erc.inductive-load-no-flyback",
        severity: "warning",
        message: `Bare DC motor '${p.id}' on pin '${p.pins.pin}' has no transistor driver or flyback diode.`,
        explanation: `DC motors exceed MCU GPIO current limits (40mA max) and generate destructive inductive kickback spikes (V = -L * di/dt) that destroy microcontroller I/O pins.`,
        target: { type: "component", id: boardRef },
        suggestion: `Use a transistor or MOSFET driver stage (e.g. 2N2222 or TIP120) with a 1N4007 clamp diode and separate motor power supply.`,
      });
    }
  }

  // Check for direct heavy/overcurrent loads driving GPIO directly (Doc §9.1: erc.pin-current)
  for (const pinUse of pinGraph.values()) {
    const hints = pinUse.nameHints.join(" ").toLowerCase();
    if (
      (hints.includes("heavy") ||
        hints.includes("overcurrent") ||
        hints.includes("solenoid") ||
        hints.includes("heater")) &&
      (pinUse.modes.has("OUTPUT") ||
        pinUse.ops.has("digitalWrite") ||
        pinUse.ops.has("analogWrite"))
    ) {
      diagnostics.push({
        ruleId: "erc.pin-current",
        severity: "warning",
        message: `GPIO output pin '${pinUse.pin}' drives high-current load exceeding absolute maximum 40mA rating.`,
        explanation: `Microcontroller output pin '${pinUse.pin}' is configured to drive a low-impedance or heavy load directly. Direct GPIO current is limited by bond wire thermal dissipation and driver FET Rdson to 40mA absolute maximum (20mA continuous recommended).`,
        target: { type: "port", id: `${boardRef}.${pinUse.pin}` },
        suggestion: `Buffer pin '${pinUse.pin}' with an external switching transistor (2N2222 NPN or 2N7000 MOSFET) or increase series load resistance to at least 125Ω.`,
      });
    }
  }

  return {
    circuit,
    peripherals: sortedPeripherals,
    pinGraph,
    diagnostics,
    assumptions,
    unresolved: combinedUnresolved,
    unresolvedItems,
  };
}
