/**
 * @license Apache-2.0
 * @s2c/arduino — Main Sketch-to-Circuit Synthesis Pipeline (Doc §12).
 */

import { createCircuit } from "@s2c/core";
import { runErc } from "@s2c/rules";
import { extractFacts } from "./extract-facts.js";
import { inferPeripherals } from "./infer.js";
import { buildPinUsageGraph } from "./pin-graph.js";
import { applyRecipes } from "./recipes/index.js";
import type { SynthesisResult, SynthesizerOptions, UnresolvedItem } from "./types.js";

/**
 * Synthesizes a verified, ERC-checked Electronic Circuit from an Arduino sketch.
 *
 * Sub-steps (Doc §12):
 * 1. Preprocess & extract annotations/macros
 * 2. Parse C++ syntax tree with Tree-sitter
 * 3. Extract facts (pinMode, digitalWrite, analogRead, pulseIn, constructors)
 * 4. Resolve constants and array indices
 * 5. Build pin-usage graph (tracking unresolved dynamic pins)
 * 6. Infer peripherals with confidence scoring & evidence
 * 7. Apply circuit engineering synthesis recipes
 * 8. Run 18-rule Electrical Rules Check (ERC) validation
 * 9. Deterministic normalization (guarantees byte-identical Circuit IR across runs)
 */
export function synthesizeSketch(
  source: string,
  options: SynthesizerOptions = {},
): SynthesisResult {
  const boardId = options.boardId || "ARDUINO_UNO_R3";
  const boardRef = options.boardRef || "U1";

  // 1-3. Extract syntactic facts from sketch via Tree-sitter AST
  const facts = extractFacts(source);

  // 4-5. Build pin usage graph with resolved constants and track unresolved items
  const unresolvedItems: UnresolvedItem[] = [];
  const pinGraph = buildPinUsageGraph(facts, unresolvedItems);

  // 6. Infer connected peripheral hardware
  const {
    peripherals,
    assumptions,
    unresolved: inferUnresolved,
  } = inferPeripherals(pinGraph, facts);

  // Merge unresolved items
  const combinedUnresolved = [...inferUnresolved, ...unresolvedItems.map((u) => u.reason)];

  // 7. Synthesize circuit with engineering recipes
  const builder = createCircuit({
    title: "Synthesized Arduino Circuit",
    description: "Generated by sketch2circuit synthesizer pipeline",
  });

  // Add the microcontroller board
  builder.addPart(boardId, boardRef);

  // Apply component and wiring recipes
  applyRecipes(builder, peripherals, {
    ...options,
    boardId,
    boardRef,
  });

  const rawCircuit = builder.build();

  // Deterministically sort components, nets, and portIds per Doc §12.5
  const components = [...rawCircuit.components].sort((a, b) => a.id.localeCompare(b.id));
  const nets = [...rawCircuit.nets]
    .map((net) => ({
      ...net,
      portIds: [...net.portIds].sort(),
    }))
    .sort((a, b) => a.id.localeCompare(b.id));

  const circuit = {
    ...rawCircuit,
    metadata: {
      ...rawCircuit.metadata,
      ...(options.timestamp ? { generatedAt: options.timestamp } : {}),
    },
    components,
    nets,
  };

  // Deterministically sort peripherals
  const sortedPeripherals = [...peripherals].sort((a, b) => a.id.localeCompare(b.id));

  // 8. Run Electrical Rules Check (ERC) validation across full 18-rule catalog
  const diagnostics = runErc(circuit);

  // Check for bare motor peripherals driving GPIO directly without driver or flyback
  for (const p of sortedPeripherals) {
    if (p.properties?.isBareMotor) {
      diagnostics.push({
        ruleId: "erc.inductive-load-no-flyback",
        severity: "warning",
        message: `Bare DC motor '${p.id}' on pin '${p.pins.pin}' has no transistor driver or flyback diode.`,
        explanation: `DC motors exceed MCU GPIO current limits (40mA max) and generate destructive inductive kickback spikes (V = -L * di/dt) that destroy microcontroller I/O pins.`,
        target: { type: "component", id: boardRef },
        suggestion: `Use a transistor or MOSFET driver stage (e.g. 2N2222 or TIP120) with a 1N4007 clamp diode and separate motor power supply.`,
      });
    }
  }

  // Check for direct heavy/overcurrent loads driving GPIO directly (Doc §9.1: erc.pin-current)
  for (const pinUse of pinGraph.values()) {
    const hints = pinUse.nameHints.join(" ").toLowerCase();
    if (
      (hints.includes("heavy") ||
        hints.includes("overcurrent") ||
        hints.includes("solenoid") ||
        hints.includes("heater")) &&
      (pinUse.modes.has("OUTPUT") ||
        pinUse.ops.has("digitalWrite") ||
        pinUse.ops.has("analogWrite"))
    ) {
      diagnostics.push({
        ruleId: "erc.pin-current",
        severity: "warning",
        message: `GPIO output pin '${pinUse.pin}' drives high-current load exceeding absolute maximum 40mA rating.`,
        explanation: `Microcontroller output pin '${pinUse.pin}' is configured to drive a low-impedance or heavy load directly. Direct GPIO current is limited by bond wire thermal dissipation and driver FET Rdson to 40mA absolute maximum (20mA continuous recommended).`,
        target: { type: "port", id: `${boardRef}.${pinUse.pin}` },
        suggestion: `Buffer pin '${pinUse.pin}' with an external switching transistor (2N2222 NPN or 2N7000 MOSFET) or increase series load resistance to at least 125Ω.`,
      });
    }
  }

  return {
    circuit,
    peripherals: sortedPeripherals,
    pinGraph,
    diagnostics,
    assumptions,
    unresolved: combinedUnresolved,
    unresolvedItems,
  };
}
